import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

from PIL import Image

PROJECT_ROOT = Path(__file__).resolve().parents[1]
SRC_DIR = PROJECT_ROOT / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))


class LocalNoUploadGenerationTests(unittest.TestCase):
    def test_youtube_local_generation_factory_does_not_start_browser(self):
        from classes.YouTube import YouTube

        with patch("classes.YouTube.webdriver.Firefox") as firefox:
            youtube = YouTube.for_local_generation(niche="IT News", language="Korean")

        firefox.assert_not_called()
        self.assertEqual(youtube.niche, "IT News")
        self.assertEqual(youtube.language, "Korean")
        self.assertEqual(youtube.images, [])
        self.assertIsNone(youtube.news_article)

    def test_placeholder_image_provider_writes_vertical_png_without_gemini_key(self):
        from classes.YouTube import YouTube

        youtube = YouTube.for_local_generation(niche="IT News", language="Korean")
        with patch("classes.YouTube.get_image_provider", return_value="placeholder"):
            path = youtube.generate_image("A Korean IT news visual about a new foldable phone")

        image_path = Path(path)
        self.assertTrue(image_path.exists())
        self.assertEqual(image_path.suffix, ".png")
        self.assertIn(str(image_path), youtube.images)

    def test_hermes_image_provider_consumes_preseeded_queue_image(self):
        from classes.YouTube import YouTube

        with tempfile.TemporaryDirectory() as tmpdir:
            queue_dir = Path(tmpdir) / "queue"
            queue_dir.mkdir(parents=True, exist_ok=True)
            queued_image = queue_dir / "test-hermes-image.png"
            Image.new("RGB", (1080, 1920), color=(10, 20, 30)).save(queued_image)

            youtube = YouTube.for_local_generation(niche="IT News", language="Korean")
            with patch("classes.YouTube.get_image_provider", return_value="hermes"), patch.dict(
                "os.environ", {"HERMES_IMAGE_QUEUE_DIR": str(queue_dir)}
            ):
                path = youtube.generate_image("A Korean IT news visual generated by Hermes")

            image_path = Path(path)
            self.assertTrue(image_path.exists())
            self.assertEqual(image_path.suffix, ".png")
            self.assertIn(str(image_path), youtube.images)
            self.assertFalse(queued_image.exists())
            self.assertIn("hermes", image_path.name)

    def test_hermes_image_provider_can_generate_via_hermes_cli_when_enabled(self):
        from classes.YouTube import YouTube

        with tempfile.TemporaryDirectory() as tmpdir:
            generated = Path(tmpdir) / "generated.png"
            Image.new("RGB", (1080, 1920), color=(30, 40, 50)).save(generated)

            def fake_run(args, **kwargs):
                self.assertEqual(args[0], "hermes")
                self.assertIn("image_gen", args)
                self.assertIn("openai-codex", args)
                self.assertIn("gpt-5.6-sol", args)
                return subprocess.CompletedProcess(args, 0, stdout=str(generated), stderr="")

            youtube = YouTube.for_local_generation(niche="IT News", language="Korean")
            with patch("classes.YouTube.get_image_provider", return_value="hermes"), patch(
                "classes.youtube_visuals.subprocess.run", side_effect=fake_run
            ), patch.dict(
                "os.environ", {"HERMES_ENABLE_CLI_IMAGE_GENERATION": "1"}, clear=False
            ):
                path = youtube.generate_image("A Korean IT news visual generated by Hermes CLI")

            image_path = Path(path)
            self.assertTrue(image_path.exists())
            self.assertEqual(image_path.suffix, ".png")
            self.assertIn(str(image_path), youtube.images)
            self.assertIn("hermes", image_path.name)
            self.assertFalse(youtube.has_placeholder_visuals)

    def test_generate_prompts_respects_configured_max_image_prompts(self):
        from classes.YouTube import YouTube

        youtube = YouTube.for_local_generation(niche="IT News", language="Korean")
        youtube.subject = "Foldable phone launch"
        youtube.script = "첫 문장입니다. 두 번째 문장입니다. 세 번째 문장입니다."
        response = json.dumps(["prompt 1", "prompt 2", "prompt 3", "prompt 4"])

        with patch.object(youtube, "generate_response", return_value=response), patch(
            "classes.YouTube.get_max_image_prompts", return_value=2
        ):
            prompts = youtube.generate_prompts()

        self.assertEqual(len(prompts), 2)
        self.assertTrue(prompts[0].startswith("prompt 1"))
        self.assertTrue(prompts[1].startswith("prompt 2"))


if __name__ == "__main__":
    unittest.main()
